### ISSUE TITLE
refactor lsst mdet

### ISSUE THREAD

**Issue by esheldon** [esheldon/metadetect#118]
I don't like this messy class hierarchy.

**Comment by beckermr** [comment]
Yes. A bunch of functions plus a single class or no classes at all is much better imho.

**Comment by esheldon** [comment]
We can use the code in lsst_measure.py (measure_weighted_moments) for this; it needs to be refactored
1. separate measurement and detection/deblend
2. make use of deblended stamps optional (to test the deblender)
3. use new style for moments so GaussMom or KSigma can be sent rather than just a gmix
