### ISSUE TITLE
don't detect in bad areas

### ISSUE THREAD

**Issue by esheldon** [esheldon/metadetect#15]
Use the symmetrized mask to propagate certain bits into the variance sent to `sep`

Avoid detecting if the ormask has these set
- STAR
- TRAIL
- others?

**Comment by esheldon** [comment]
we need a sheared version of the ormask

or we need the unsheared position to go and get the flags for the pixel of the center, to cut after the fact

**Comment by beckermr** [comment]
We have all of these cuts now. Closing.
