### ISSUE TITLE
reuse runners + bootstrappers in joint fits

### ISSUE THREAD

**Issue by beckermr** [esheldon/metadetect#206]
cc @esheldon

**Comment by esheldon** [comment]
You can make a single bootstrapper and re-use it.

Note the option of ignoring failed psfs.

**Comment by esheldon** [comment]
(which is the default)

**Comment by beckermr** [comment]
We should turn off ignoring failed psfs.

**Comment by esheldon** [comment]
I think we probably do want it.  How it works is that it can remove *epochs* from the ObsList.  But it raises if all epochs would be removed.  In other words, it does not allow a band to drop out.

**Comment by esheldon** [comment]
This is how `BootPSFFailure` gets raised in the fitting

**Comment by beckermr** [comment]
Ahhhh. That's fine then.

**Comment by esheldon** [comment]
OK, good, just wanted to discuss it to make sure we agreed.
