### ISSUE TITLE
write codes for metadetect with stack objects

### ISSUE THREAD

**Issue by esheldon** [esheldon/metadetect#32]

**Comment by beckermr** [comment]
Can you be a bit more specific? You mean like stack exposures or stack measurements?

**Comment by esheldon** [comment]
I was thinking perhaps it would be better to have this code use more primitive lsst objects rather than Observations, but after looking again at how the code works it probably won't gain us anything

**Comment by beckermr** [comment]
Right. I think we need to interface with the stack in one spot and then leave the rest the same.
