### ISSUE TITLE
add bits to mask input for the metadetect code

### ISSUE THREAD

**Issue by esheldon** [esheldon/metadetect#71]
The `bmask` will be checked for those bits (not the ormask), and a boolean `mask=` will be sent to sep for detection

The current motivation for this is star masking

**Comment by beckermr** [comment]
This was already done when the code moved over to sxdes, right?

**Comment by esheldon** [comment]
I think this does what we want

https://github.com/esheldon/metadetect/blob/master/metadetect/detect.py#L222
https://github.com/esheldon/metadetect/blob/master/metadetect/detect.py#L251

**Comment by beckermr** [comment]
Yep. Closing this issue.
