### ISSUE TITLE
Clean up old masking options

### ISSUE THREAD

**Issue by beckermr** [esheldon/metadetect#72]
There are a bunch of old masking options that don't do anything and aren't useful. We should get rid of them.

**Comment by esheldon** [comment]
Good catch, I had forgotten about that stuff

**Comment by esheldon** [comment]
I think your tests have addressed all of those except tapebump.  But for Y6 we really don't expect tapebumps to be an issue.

**Comment by esheldon** [comment]
I propose we remove all these and rely on mfrac

we will be setting the mask for sep detection based on the star masking only. Is that good enough?

**Comment by beckermr** [comment]
Yeah I agree with all of this. The mfrac cut needs testing though.

**Comment by esheldon** [comment]
Do you mean tests other than the shear recover tests you have done so far?

**Comment by beckermr** [comment]
Yeah. Those all use a cut on the ormask at the detection's center.

**Comment by esheldon** [comment]
The most recent tests?  I thought those were cuts on mfrac.

**Comment by beckermr** [comment]
Not yet. I have not gotten those done yet.

**Comment by esheldon** [comment]
OK, let's wait until we get those results then I'll clean this up
