### ISSUE TITLE
add the mask_frac calculations used in DES

### ISSUE THREAD

**Issue by esheldon** [esheldon/metadetect#95]

**Comment by beckermr** [comment]
Is the proper coadd masked fraction being computed in the coadding code?

**Comment by esheldon** [comment]
see https://github.com/LSSTDESC/descwl_coadd/issues/48

**Comment by esheldon** [comment]
See https://github.com/LSSTDESC/descwl_coadd/pull/53

we will need to run the gauss aper mfrac code in metadetect
